from .vlm_sam3_bridge import NODE_CLASS_MAPPINGS as _VLM_MAP, NODE_DISPLAY_NAME_MAPPINGS as _VLM_NAMES
from .samhera_utils import NODE_CLASS_MAPPINGS as _UTILS_MAP, NODE_DISPLAY_NAME_MAPPINGS as _UTILS_NAMES

NODE_CLASS_MAPPINGS = {**_VLM_MAP, **_UTILS_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**_VLM_NAMES, **_UTILS_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
